hungry/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import index

urlpatterns = [
    path('', index, name='index'),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
]

users/urls.py
from django.contrib import admin
from django.urls import path
from users.views import create_customer, dashboard, create_dog

app_name = 'users'

urlpatterns = [
    path('create_customer/', create_customer, name='create_customer'),
    path('dashboard/', dashboard, name='dashboard'),
    path('create_dog/', create_dog, name='create_dog')
]

users/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser


# Create your models here.


class User(AbstractUser):
    is_restaurant = models.BooleanField(default=False)
    is_customer = models.BooleanField(default=False)


class Restaurant(models.Model):
    user = models.OneToOneField(User, primary_key=True, on_delete=models.CASCADE)
    restaurant_name = models.CharField(max_length=50)

    def __str__(self):
        return self.restaurant_name


class Customer(models.Model):
    user = models.OneToOneField(User, primary_key=True, on_delete=models.CASCADE)
    address = models.CharField(max_length=200)

    def __str__(self):
        return self.user.get_full_name()


class Dog(models.Model):
    name_dog = models.CharField(max_length=50)

users/forms.py
from django import forms
from django.forms import ModelForm, PasswordInput
from django.contrib.auth.forms import UserCreationForm
from users.models import Dog, Customer, Restaurant

from users.models import Restaurant, User


class CustomerSignUpForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User


class CustomerForm(ModelForm):

    class Meta:
        model = Customer
        fields = ['address']



class DogForm(ModelForm):
    class Meta:
        model = Dog
        fields = ['name_dog']

users/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from users.models import User
from users.forms import CustomerSignUpForm, DogForm, CustomerForm
from django.shortcuts import render
from users.models import Restaurant, Dog
from django.views.generic.edit import CreateView

# Create your views here.


def create_customer(request):
    if request.method != 'POST':
        form = CustomerSignUpForm
        form2 = CustomerForm
    else:
        form = CustomerSignUpForm(data=request.POST)

        if form.is_valid():
            new_restaurant = form.save()
            new_restaurant.is_customer = True
            new_restaurant.save()
            # auth_rest = authenticate(username = new_restaurant.username, password = new_restaurant.password)
            login(request, new_restaurant)
            return HttpResponseRedirect(reverse('users:dashboard'))

    context = {'form': form, 'form2':form2}
    return render(request, 'users/create_customer.html', context)


def dashboard(request):
    user = request.user
    if user.is_customer:
        customer = user
        context = {'customer':customer}
        return render(request, 'users/customer_dashboard.html', context)
    else:
        restaurant = user
        context = {'restaurant':restaurant}
        return render(request,'users/restaurant_dashboard.html', context)


def index(request):
    template = 'users/index.html'
    return render(request, template)


def create_dog(request):
    form = DogForm
    template = 'users/dog_form.html'
    dog_list = Dog.objects.all()
    user = request.user

    if request.method != 'POST':
        context = {'form':form, 'dog_list':dog_list}
    else:
        new_dog = form(data=request.POST)
        new_dog.save()
        dog_list = Dog.objects.all()
        user = request.user
        context = {'dog_list':dog_list}
        return render(request, 'users/customer_dashboard.html', context)

    return render(request, template, context)

users/templates/users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hungry</title>
</head>
<body>
<a href="{% url 'index' %}">Homepage</a>
<a href="{% url 'users:dashboard' %}">Dashboard</a>
<a href="{% url 'users:create_dog' %}">Create Dog</a>
{#TODO create a dashboard that redirects to different spots depending on if you are restaurant or customer#}

{% block content %}
{% endblock %}


</body>
</html>

users/templates/users/create_customer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Restaurant Sign Up</title>
</head>
<body>

<h1>Register a Restaurant Here</h1>

<p>
    <form action="{% url 'users:create_customer' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    {{ form2.as_p }}

    <button type="submit">Register</button>
    <input type="hidden" name="next" value="{% url 'users:dashboard' %}" />
    </form>

</p>
</body>
</html>

users/templates/users/customer_dashboard.html
{% extends 'users/base.html' %}

{% block content%}

    This will be the customer dashboard!

    Upcoming meals:<br>
    History<br>
    Etc.<br>

    <br>
    {% for dog in dog_list %}
    {{ dog.name_dog }}<br>
    {% endfor %}
    <br>
    {{ user.first_name }}

{% endblock %}

users/templates/users/dog_form.html
{% extends 'users/base.html' %}

{% block content %}

    <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
    <input type="hidden" name="next" value="{% url 'users:dashboard' %}" />
    </form>

{% endblock %}

users/templates/users/index.html
{% extends 'users/base.html' %}

{% block content%}
<p>find great food here</p>
<a href="{% url 'users:create_customer' %}">Customer Sign Up</a>
{% endblock %}

users/templates/users/restaurant_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Restaurant Sign Up</title>
</head>
<body>
<p>Test</p>
</body>
</html>

users/templates/users/restaurant_dashboard.html
{% extends 'users/base.html' %}

{% block content %}
<br>

    {{ restaurant }}

{% endblock %}